name: retro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter95: ^0.0.7
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  shared_preferences: ^0.5.7+3
  assets_audio_player: ^2.0.6+4
  flutter_swiper: ^1.1.6
  youtube_player_flutter: ^6.1.0+4
  flutter_launcher_icons: ^0.7.3
  url_launcher: ^5.4.11
  custom_splash: ^0.0.2

  


 






dev_dependencies:
   flutter_test:
    sdk: flutter
flutter_icons:    
 android: "launcher_icon"    
 ios: true    
 image_path: "images/logo.png"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/google.jpg
    - images/gamesnew.png
    - images/retro.png
    - images/book.jpg
    - images/book1.jpg
    - images/book2.jpg
    - images/book3.jpg
    - images/game.png
    - images/game1.jpg
    - images/game3.jpg
    - images/game4.png
    - images/game5.jpg
    - images/game6.png
    - images/game7.png
    - images/game8.jpg
    - images/game9.png
    - images/logo.png
    - images/videopic.png
    - images/audio.png
    - images/retro1.jpg
    - images/retro2.jpg
    - images/retro3.jpg
    - images/retro4.jpg
    - images/retro5.jpg
    - images/retro6.jpg
    - audio/Lacalin.mp3
    - audio/really.mp3
    - audio/summerof69.mp3
    - audio/retro.mp3
    - images/summer.jpg
    - images/miachel.jpg
    - images/lacalin.jpg
    - images/bob.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true